# Generated by Django 5.2.4 on 2026-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0002_clubsettings_event_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
