# Generated by Django 5.2.4 on 2026-02-11 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0003_clubsettings_instagram_url_clubsettings_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='password',
            field=models.CharField(blank=True, help_text='Stored password for user creation upon approval', max_length=128, null=True),
        ),
    ]
